# Generated by Django 6.1 on 2026-08-31 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(db_index=True, max_length=30, verbose_name='Token Number')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('CALLED', 'Called to Counter'), ('SERVING', 'Currently Serving'), ('COMPLETED', 'Service Completed'), ('SKIPPED', 'Customer Skipped / Absent'), ('CANCELLED', 'Cancelled by User')], db_index=True, default='WAITING', max_length=20, verbose_name='Status')),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Joined At')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Called At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('counter_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Assigned Counter')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='services.service', verbose_name='Service Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Customer User')),
            ],
            options={
                'verbose_name': 'Queue Token',
                'verbose_name_plural': 'Queue Tokens',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['service', 'status', 'joined_at'], name='queues_queu_service_edcbe6_idx'), models.Index(fields=['user', 'status'], name='queues_queu_user_id_8c7af4_idx'), models.Index(fields=['status', 'joined_at'], name='queues_queu_status_301c12_idx')],
            },
        ),
    ]
