# Generated by Django 6.1 on 2026-08-31 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Service Name')),
                ('prefix', models.CharField(default='A', help_text="Token code prefix (e.g. 'A' creates tokens like 'A-001', 'A-024')", max_length=5, verbose_name='Token Prefix')),
                ('description', models.TextField(blank=True, default='', verbose_name='Service Description')),
                ('average_service_time', models.PositiveIntegerField(default=5, help_text='Average duration per customer in minutes', verbose_name='Avg Service Time (mins)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
    ]
